### ISSUE TITLE
Default path creates literal "Get-Location" dir

### ISSUE THREAD

**Issue by ofolis** [TCNOco/TcNo-TCHT#19]
Hello!

Just ran the `spigot.ps1` script and it worked very well. I opted for default location, but instead of creating `spigot/` it created `Get-Location/spigot/`.

I think I tracked the issue down to here:
https://github.com/TCNOco/TcNo-TCHT/blob/5d9f130d2149a3a167862037183227e47474f142/PowerShell/Software/spigot.ps1#L48

I believe this line should be:
`    $answer = Join-Path $(Get-Location) "spigot\"`

Anyway, thanks again for this tool!

**Comment by TCNOco** [comment]
Yeah this seems to be correct.
```ps
> Join-Path Get-Location "spigot\"
Get-Location\spigot\

> Join-Path $(Get-Location) "spigot\"
C:\Users\tcno\spigot\
```

Thank you for this. I an pushing the fix.
