### ISSUE TITLE
AttributeError: 'Llama' object has no attribute 'ctx'

### ISSUE THREAD

**Issue by firerflystar** [TCNOco/TcNo-TCHT#5]
i got below error when startup that install on windows 10 21H2 "iex (irm vicuna.tc.ht)"

Gradio HTTP request redirected to localhost :)
bin D:\Vicuna\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\libbitsandbytes_cpu.dll
D:\Vicuna\oobabooga_windows\installer_files\env\lib\site-packages\bitsandbytes\cextension.py:33: UserWarning: The installed version of bitsandbytes was compiled without GPU support. 8-bit optimizers, 8-bit multiplication, and GPU quantization are unavailable.
  warn("The installed version of bitsandbytes was compiled without GPU support. "
Loading eachadea_ggml-vicuna-7b-1-1...
llama.cpp weights detected: models\eachadea_ggml-vicuna-7b-1-1\ggml-vicuna-7b-1.1-q4_1.bin

llama.cpp: loading model from models\eachadea_ggml-vicuna-7b-1-1\ggml-vicuna-7b-1.1-q4_1.bin
Traceback (most recent call last):
  File "D:\Vicuna\oobabooga_windows\text-generation-webui\server.py", line 912, in <module>
    shared.model, shared.tokenizer = load_model(shared.model_name)
  File "D:\Vicuna\oobabooga_windows\text-generation-webui\modules\models.py", line 109, in load_model
    model, tokenizer = LlamaCppModel.from_pretrained(model_file)
  File "D:\Vicuna\oobabooga_windows\text-generation-webui\modules\llamacpp_model_alternative.py", line 29, in from_pretrained
    self.model = Llama(**params)
  File "D:\Vicuna\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 107, in __init__
    self.ctx = llama_cpp.llama_init_from_file(
  File "D:\Vicuna\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama_cpp.py", line 152, in llama_init_from_file
    return _lib.llama_init_from_file(path_model, params)
OSError: [WinError -1073741795] Windows Error 0xc000001d
Exception ignored in: <function Llama.__del__ at 0x0000024421D2AF80>
Traceback (most recent call last):
  File "D:\Vicuna\oobabooga_windows\installer_files\env\lib\site-packages\llama_cpp\llama.py", line 785, in __del__
    if self.ctx is not None:
AttributeError: 'Llama' object has no attribute 'ctx'

**Comment by TCNOco** [comment]
This is an issue with Oobabooga windows and the model.

I don't remember what caused this, as I did run in to it as well, but it was either not having enough memory to run the model,

or trying to start Oobabooga after installing as CPU only with GPU settings,

or either that it has `--wbits 4 --groupsize 128` or is missing, but needs them in the startup file next to `python server.py`

Try the last option here by editing `start_vicuna-cpu-7B.bat`, or whichever bat file points to your model.

**Comment by firerflystar** [comment]
My CPU is: 2 X Intel(R) Xeon(R) CPU E5-2660 0 @ 2.20GHz   2.20 GHz
Memory Ram: 64.0 GB
GPU: 1050ti ( i choose only CPU because poor VRAM to run)
System: windows 10 21H2

it is still same error after edited "start_vicuna-cpu-7B.bat" : 
`python server.py --auto-devices --chat --model eachadea_ggml-vicuna-7b-1-1 --wbits 4 --groupsize 128`

and same OSError: [WinError -1073741795] Windows Error 0xc000001d in [text-generation-webui](https://github.com/oobabooga/text-generation-webui) , i am trying to move ggml model there (ggml-vicuna-7b-1.1-q4_1.bin):
![image](https://user-images.githubusercontent.com/62865237/233609545-759403ec-fd78-411b-b9f8-2e0233e25130.png)

**Comment by firerflystar** [comment]
i am trying to remove GPU from computer slot, but same output error.

**Comment by firerflystar** [comment]
i found reasons here: https://github.com/LostRuins/koboldcpp/issues/61

**Comment by TCNOco** [comment]
Great! A solution. You just added `--noavx2` in the launch bat? For AMD GPU? CPU?
